namespace EZFormsPrototype.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using EZFormsPrototype.Models;
    using System.Collections.Generic;

    internal sealed class Configuration : DbMigrationsConfiguration<EZFormsPrototype.DAL.FormContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(EZFormsPrototype.DAL.FormContext context)
        {
            //  This method will be called after migrating to the latest version.
            var forms = new List<Form>
            {
                new Form { Title = "Test Form", Description = "A form automatically generated by the seed for test purposes"}
            };

            forms.ForEach(f => context.Forms.AddOrUpdate(p => p.Title, f));
            context.SaveChanges();
            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.
        }
    }
}
